### ISSUE TITLE
`Cannot destructure property 'operator' of 'fail.diag' as it is undefined.`

### ISSUE THREAD

**Issue by ehmicky** [Munter/netlify-plugin-checklinks#73] opened 2020-05-04 16:17 UTC
The following error message is appearing in some builds:

```
Cannot destructure property 'operator' of 'fail.diag' as it is undefined. 
    /opt/build/repo/node_modules/tap-spot/index.js:88:17 
    /opt/build/repo/node_modules/tap-spot/index.js:87:13 Parser.<anonymous>
    events.js:315:20 Parser.emit
    /opt/build/repo/node_modules/tap-parser/node_modules/minipass/index.js:414:25 Parser.emit
    /opt/build/repo/node_modules/tap-parser/index.js:442:12 Parser.emitComplete
    /opt/build/repo/node_modules/tap-parser/index.js:413:10 Parser.end
    /opt/build/repo/node_modules/duplexer/index.js:47:39 Stream.method [as end]
    internal/streams/legacy.js:46:10 Stream.onend
    events.js:327:22 Stream.emit
    /opt/build/repo/node_modules/through/index.js:34:23 drain
    /opt/build/repo/node_modules/through/index.js:45:5 Stream.stream.queue.stream.push [as queue]
    /opt/build/repo/node_modules/through/index.js:15:35 Stream.end
    /opt/build/repo/node_modules/through/index.js:65:9 _end
    /opt/build/repo/node_modules/through/index.js:74:5 Stream.stream.end
    /opt/build/repo/node_modules/@munter/tap-render/index.js:84:16 Stream.close
    /opt/build/repo/node_modules/netlify-plugin-checklinks/lib/index.js:60:23 onPostBuild
    src/plugins/child/run.js:13:3 async Object.run
    src/plugins/child/main.js:38:38 async handleEvent
    src/plugins/ipc.js:97:9 async process.<anonymous>
```

This appears to be from the [following line of code](https://github.com/Munter/tap-spot/blob/6389e2a00ba7f8b89a6cd25ba140771dc9146042/index.js#L88) with `fail.diag` being `undefined`. @Munter Do you know what the error might be?

**Comment by ehmicky** [comment] 2020-05-05 11:01
The following related error message is also appearing:

```
Cannot destructure property `operator` of 'undefined' or 'null'. 
    /opt/build/repo/node_modules/tap-spot/index.js:88:57 
    /opt/build/repo/node_modules/tap-spot/index.js:87:13 Parser.<anonymous>
    events.js:198:13 Parser.emit
    /opt/build/repo/node_modules/minipass/index.js:414:25 Parser.emit
    /opt/build/repo/node_modules/tap-parser/index.js:442:12 Parser.emitComplete
    /opt/build/repo/node_modules/tap-parser/index.js:413:10 Parser.end
    /opt/build/repo/node_modules/duplexer/index.js:47:39 Stream.method [as end]
    internal/streams/legacy.js:42:10 Stream.onend
    events.js:203:15 Stream.emit
    /opt/build/repo/node_modules/through/index.js:34:23 drain
    /opt/build/repo/node_modules/through/index.js:45:5 Stream.stream.queue.stream.push [as queue]
    /opt/build/repo/node_modules/through/index.js:15:35 Stream.end
    /opt/build/repo/node_modules/through/index.js:65:9 _end
    /opt/build/repo/node_modules/through/index.js:74:5 Stream.stream.end
    /opt/build/repo/node_modules/@munter/tap-render/index.js:84:16 Stream.close
    /opt/build/repo/node_modules/netlify-plugin-checklinks/lib/index.js:60:23 onPostBuild
```

**Comment by Munter** [comment] 2022-03-22 09:21
Marking as duplicate of https://github.com/Munter/netlify-plugin-checklinks/issues/555 where we have more diagnostics available

**Closed by Munter** 2022-03-22 09:21 UTC
