### ISSUE TITLE
TypeError: Cannot destructure property 'operator' of 'todo.diag' as it is undefined.

### ISSUE THREAD

**Issue by Licenser** [Munter/netlify-plugin-checklinks#559] opened 2021-10-27 09:20 UTC
We get this error when using the plugin on https://github.com/tremor-rs/tremor-www

```
9:07:18 PM: ────────────────────────────────────────────────────────────────
9:07:18 PM:   Plugin "netlify-plugin-checklinks" internal error             
9:07:18 PM: ────────────────────────────────────────────────────────────────
9:07:18 PM: ​
9:07:18 PM:   Error message
9:07:18 PM:   TypeError: Cannot destructure property 'operator' of 'todo.diag' as it is undefined.
9:07:18 PM: ​
9:07:18 PM:   Plugin details
9:07:18 PM:   Package:        netlify-plugin-checklinks
9:07:18 PM:   Version:        4.1.1
9:07:18 PM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
9:07:18 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
9:07:18 PM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
9:07:18 PM: ​
9:07:18 PM:   Error location
9:07:18 PM:   In "onPostBuild" event in "netlify-plugin-checklinks" from Netlify app
9:07:18 PM:       at /opt/build/repo/.netlify/plugins/node_modules/tap-spot/index.js:72:17
9:07:18 PM:       at Array.forEach (<anonymous>)
9:07:18 PM:       at Parser.<anonymous> (/opt/build/repo/.netlify/plugins/node_modules/tap-spot/index.js:71:13)
9:07:18 PM:       at Parser.emit (events.js:314:20)
9:07:18 PM:       at Parser.emit (/opt/build/repo/.netlify/plugins/node_modules/minipass/index.js:414:25)
9:07:18 PM:       at Parser.emitComplete (/opt/build/repo/.netlify/plugins/node_modules/tap-parser/index.js:442:12)
9:07:18 PM:       at Parser.end (/opt/build/repo/.netlify/plugins/node_modules/tap-parser/index.js:413:10)
9:07:18 PM:       at Stream.method [as end] (/opt/build/repo/.netlify/plugins/node_modules/duplexer/index.js:47:39)
9:07:18 PM:       at Stream.onend (internal/streams/legacy.js:46:10)
9:07:18 PM:       at Stream.emit (events.js:326:22)
9:07:18 PM:       at drain (/opt/build/repo/.netlify/plugins/node_modules/through/index.js:34:23)
9:07:18 PM:       at Stream.stream.queue.stream.push [as queue] (/opt/build/repo/.netlify/plugins/node_modules/through/index.js:45:5)
9:07:18 PM:       at Stream.end (/opt/build/repo/.netlify/plugins/node_modules/through/index.js:15:35)
9:07:18 PM:       at _end (/opt/build/repo/.netlify/plugins/node_modules/through/index.js:65:9)
9:07:18 PM:       at Stream.stream.end (/opt/build/repo/.netlify/plugins/node_modules/through/index.js:74:5)
9:07:18 PM:       at Stream.close (/opt/build/repo/.netlify/plugins/node_modules/@munter/tap-render/index.js:84:16)
9:07:18 PM:       at onPostBuild (/opt/build/repo/.netlify/plugins/node_modules/netlify-plugin-checklinks/lib/index.js:60:23)
9:07:18 PM:       at async Object.run (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/run.js:20:3)
9:07:18 PM:       at async handleEvent (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
9:07:18 PM:       at async process.<anonymous> (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
9:07:18 PM: ​
9:07:18 PM:   Resolved config
9:07:18 PM:   build:
9:07:18 PM:     command: npm run build
9:07:18 PM:     commandOrigin: ui
9:07:18 PM:     environment:
9:07:18 PM:       - REVIEW_ID
9:07:18 PM:     publish: /opt/build/repo/build
9:07:18 PM:     publishOrigin: ui
9:07:18 PM:   plugins:
9:07:18 PM:     - inputs: {}
9:07:18 PM:       origin: ui
9:07:18 PM:       package: netlify-plugin-checklinks
9:07:18 PM:     - inputs: {}
9:07:18 PM:       origin: ui
9:07:18 PM:       package: netlify-plugin-a11y
9:07:18 PM:     - inputs: {}
9:07:18 PM:       origin: ui
9:07:18 PM:       package: netlify-plugin-inline-critical-css
```

**Comment by Munter** [comment] 2022-03-22 09:20
Marking as duplicate of https://github.com/Munter/netlify-plugin-checklinks/issues/555

**Closed by Munter** 2022-03-22 09:20 UTC
Labels: bug
